events {}

http {
    server {
        listen 80;

        location / {
            # Redirect any request on port 80 directly to the Scalar API documentation
            return 301 http://localhost:8080/scalar/v1;
        }
    }
}
